# Site settings
title: Powers vested in me by no one in particular
email: john@stacked.events
description: > # this means to ignore newlines until "baseurl:"
  A place for hackathon resources, mostly.
baseurl: "/vested-by-no-one" # the subpath of your site, e.g. /blog/
url: "http://jnconkle.github.io" # the base hostname & protocol for your site
twitter_username: jnconkle
github_username:  jnconkle

# Build settings
markdown: kramdown
